// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from './routes/_app.tsx'
import * as $1 from './routes/album/[id].tsx'
import * as $2 from './routes/image/[id].tsx'
import * as $3 from './routes/images.ts'

const manifest = {
  routes: {
    './routes/_app.tsx': $0,
    './routes/album/[id].tsx': $1,
    './routes/image/[id].tsx': $2,
    './routes/images.ts': $3,
  },
  islands: {},
  baseUrl: import.meta.url,
}

export default manifest
