// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $album_id_ from "./routes/album/[id].tsx";
import * as $image_id_ from "./routes/image/[id].tsx";
import * as $images from "./routes/images.ts";
import * as $user_id_ from "./routes/user/[id].tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/album/[id].tsx": $album_id_,
    "./routes/image/[id].tsx": $image_id_,
    "./routes/images.ts": $images,
    "./routes/user/[id].tsx": $user_id_,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
